[cerebrium.deployment]
name = "celebrium-docker-prod"
python_version = "3.10"
disable_auth = true
include = ['./*']
exclude = ['.*']
shell_commands = []

[cerebrium.hardware]
cpu = 2.0
memory = 8.0
compute = "CPU"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"


